[tool.poetry]
name = "poetry-scmver"
version = "0.1.2.dev6"
description = "Plugin for Poetry to enable dynamic versioning based on VCS tags for semver"
license = "MIT"
authors = ["Lorenzo A. Garcia Calzadilla <lorenzogarciacalzadilla@gmail.com>"]
readme = "README.md"
keywords = ['poetry', 'scm', 'version', 'plugin']
include = ["zzz_poetry_scmver.pth"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Plugins",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Build Tools",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Topic :: Software Development :: Version Control",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Software Distribution",
    "Topic :: Utilities"
]


[tool.poetry.dependencies]
python = "^3.7"
tomlkit = "*"
poetry = "*"
scmver = "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[[tool.poetry.source]]
name = 'private'
url = 'http://localhost:8000/simple'


[tool.scmver]
enable = true
write_to = "poetry_scmver/version.py"
#spec = "major.dev"
#spec = "minor.dev"
spec = "micro.dev"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

