dist: bionic
language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
    - eggs
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION="5.2"
    - python: "3.7"
      env: PLONE_VERSION="5.2"
  sudo: true
  fast_finish: true
before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt
  - sed -ie "s#test-5.2.x.cfg#test-$PLONE_VERSION.x.cfg#" buildout.cfg
  - bin/buildout -N -t 3 annotate
install:
  - bin/buildout -N -t 3
script:
  - bin/test
