---
- hosts: undercloud
  vars:
    metadata:
      name: Collect and verify role flavors
      description: >
        This validation checks the flavors assigned to roles exist and have the
        correct capabilities set.
      groups:
      - pre-deployment
      - pre-upgrade
  tasks:
  - include_tasks: tasks/deprecation.yaml

  - name: Collect and check the flavors
    check_flavors:
      roles_info: "{{ lookup('roles_info', wantlist=True) }}"
      flavors: "{{ lookup('nova_flavors', wantlist=True) }}"
    register: flavor_result

  - name: Verify the profiles
    verify_profiles:
      nodes: "{{ lookup('ironic_nodes', wantlist=True) }}"
      flavors: "{{ flavor_result.flavors }}"
