---
- hosts: undercloud, overcloud
  vars:
    metadata:
      name: Verify DNS
      description: >
        Verify that the DNS resolution works
      groups:
        - pre-deployment
    server_to_lookup: example.com
  tasks:
  - include_tasks: tasks/deprecation.yaml

  - name: Ensure DNS resolution works
    command: "getent hosts {{ server_to_lookup }}"
    changed_when: False
