---
- hosts: undercloud
  vars:
    metadata:
      name: Verify undercloud fits the CPU core requirements
      description: >
        Make sure that the undercloud has enough CPU cores.

        https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/7/html/Director_Installation_and_Usage/sect-Undercloud_Requirements.html
      groups:
        - prep
        - pre-introspection
    min_undercloud_cpu_count: 8
  tasks:
  - include_tasks: tasks/deprecation.yaml

  - name: Verify the number of CPU cores
    fail:
      msg: >-
        There are {{ ansible_processor_vcpus }} cores in the system,
        but there should be at least {{ min_undercloud_cpu_count }}
    failed_when: "ansible_processor_vcpus|int < min_undercloud_cpu_count|int"
