# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 14:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_auto_20160520_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedpermission',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedpermission',
            name='namespace',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedpermission',
            name='object_id',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seedpermission',
            name='type',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
