# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0007_auto_20160524_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedpermission',
            name='object_id',
            field=models.TextField(blank=True),
        ),
    ]
