
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-09T12:49:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d3f122f65eed8dca5a2da476e1106ee29e243e2",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
