
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-15T18:16:52-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e75e8e9291e7bc195fb961f95efba7ea3b7ca70",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
