[tool.poetry]
name = "test_exe_matrix"
version = "0.0.12"
license = "GPL-2.1 or CECILL-2.1"
authors = [
    "Feth AREZKI <text_exe_matrix@tuttu.info>"
]
readme = 'README.rst'

repository = "https://framagit.org/feth/test_exe_matrix"
homepage = "https://framagit.org/feth/test_exe_matrix"

include = ["**/matrix.yaml"]


[tool.poetry.dependencies]
python = ">= 3.5"
pytest = "5.3.1"
PyYAML = ">= 5.2"

[tool.poetry.scripts]
test_exe_matrix = 'test_exe_matrix.main:entrypoint'
