# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-10 05:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("scheduler", "0003_queuetaskrun")]

    operations = [
        migrations.CreateModel(
            name="ScheduleFailure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField()),
                ("initiated_at", models.DateTimeField()),
                ("reason", models.TextField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.Schedule",
                    ),
                ),
            ],
        )
    ]
