[tool.poetry]
name = "reposync"
version = "0.6.2"
description = "Organize git repositories."
authors = ["Devin Alvaro <devin.alvaro@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "http://github.com/devinalvaro/reposync"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Version Control :: Git",
]

[tool.poetry.dependencies]
python = "^3.7"
fire = "^0.2.1"
gitpython = "^3.0.5"
pyaml = "^19.12.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
reposync = 'reposync.console:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
