language: python
env:
  global:
    - CI=true

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5

    - os: osx
      sudo: required
      language: generic

#  Manually install python on osx
install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then

      brew update;
      brew install python3;
      python3 -m venv venv;
      source venv/bin/activate;
      pip install pip --upgrade
      pip install setuptools --upgrade
      pip install nose --upgrade
      pip install --install-option='--no-cython-compile' cython
      pip install numpy
      pip install bcolz
      python setup.py build_ext --inplace

  else
      pip install pip --upgrade
      pip install setuptools --upgrade
      pip install nose --upgrade
      pip install --install-option='--no-cython-compile' cython
      pip install numpy
      pip install bcolz
      python setup.py build_ext --inplace
  fi

script:
- nosetests bquery
notifications:
email: false

