
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-10T17:51:57+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2367e703c23ed9bf2d1577b29324e7f2c7ea6c24",
 "version": "v0.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
