
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-05T16:16:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2ca1ea30b83475953127b3fe6db2cc36f4b4a49b",
 "version": "0.3.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
