branches:
  only:
    - master
    - develop

# appveyor.yml
# reported on https://github.com/tox-dev/tox-conda/issues/30
---
environment:
  PYTHONBUFFERED: 1
  MINICONDA: C:\\Miniconda3-x64
  matrix:
  - TOXENV: py36
    PYTHON_HOME: C:\Python36-x64
    PYTHON_VERSION: '3.6'
    PYTHON_ARCH: '64'
    _CONDA_EXE: C:\Miniconda3-x64\Library\bin\..\..\Scripts\conda.exe
  - TOXENV: py37
    PYTHON_HOME: C:\Python37-x64
    PYTHON_VERSION: '3.7'
    PYTHON_ARCH: '64'
    _CONDA_EXE: C:\Miniconda3-x64\Library\bin\..\..\Scripts\conda.exe

build: off

install:
- '%PYTHON_HOME%\python -m pip install --upgrade pip'
- '%PYTHON_HOME%\python -m pip install numpy'
- '%PYTHON_HOME%\python -m pip install tox'
- '%PYTHON_HOME%\python -m pip install git+git://github.com/tox-dev/tox-conda#egg=tox-conda'
- 'SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PYTHON%\Lib\site-packages\numpy.libs;%PATH%'

test_script:
- ps: dir 'env:'
- '%PYTHON_HOME%\Scripts\tox -e %TOXENV%'

