# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/gaussian_camera_config.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GaussianCameraConfigForm(object):
    def setupUi(self, GaussianCameraConfigForm):
        GaussianCameraConfigForm.setObjectName("GaussianCameraConfigForm")
        GaussianCameraConfigForm.resize(301, 261)
        self.spotOscillationCheckBox = QtWidgets.QCheckBox(GaussianCameraConfigForm)
        self.spotOscillationCheckBox.setGeometry(QtCore.QRect(10, 42, 141, 20))
        self.spotOscillationCheckBox.setObjectName("spotOscillationCheckBox")
        self.spotOscillationGroupBox = QtWidgets.QGroupBox(GaussianCameraConfigForm)
        self.spotOscillationGroupBox.setEnabled(False)
        self.spotOscillationGroupBox.setGeometry(QtCore.QRect(12, 59, 282, 171))
        self.spotOscillationGroupBox.setCheckable(False)
        self.spotOscillationGroupBox.setObjectName("spotOscillationGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.spotOscillationGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xAmpLabel = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.xAmpLabel.setObjectName("xAmpLabel")
        self.horizontalLayout.addWidget(self.xAmpLabel)
        self.xAmpLineEdit = QtWidgets.QLineEdit(self.spotOscillationGroupBox)
        self.xAmpLineEdit.setObjectName("xAmpLineEdit")
        self.horizontalLayout.addWidget(self.xAmpLineEdit)
        self.xAmpUnits = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.xAmpUnits.setObjectName("xAmpUnits")
        self.horizontalLayout.addWidget(self.xAmpUnits)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.xFreqLabel = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.xFreqLabel.setObjectName("xFreqLabel")
        self.horizontalLayout_2.addWidget(self.xFreqLabel)
        self.xFreqLineEdit = QtWidgets.QLineEdit(self.spotOscillationGroupBox)
        self.xFreqLineEdit.setObjectName("xFreqLineEdit")
        self.horizontalLayout_2.addWidget(self.xFreqLineEdit)
        self.xFreqUnits = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.xFreqUnits.setObjectName("xFreqUnits")
        self.horizontalLayout_2.addWidget(self.xFreqUnits)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.yAmpLabel = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.yAmpLabel.setObjectName("yAmpLabel")
        self.horizontalLayout_3.addWidget(self.yAmpLabel)
        self.yAmpLineEdit = QtWidgets.QLineEdit(self.spotOscillationGroupBox)
        self.yAmpLineEdit.setObjectName("yAmpLineEdit")
        self.horizontalLayout_3.addWidget(self.yAmpLineEdit)
        self.yAmpUnits = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.yAmpUnits.setObjectName("yAmpUnits")
        self.horizontalLayout_3.addWidget(self.yAmpUnits)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yFreqLabel = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.yFreqLabel.setObjectName("yFreqLabel")
        self.horizontalLayout_4.addWidget(self.yFreqLabel)
        self.yFreqLineEdit = QtWidgets.QLineEdit(self.spotOscillationGroupBox)
        self.yFreqLineEdit.setObjectName("yFreqLineEdit")
        self.horizontalLayout_4.addWidget(self.yFreqLineEdit)
        self.yFreqUnits = QtWidgets.QLabel(self.spotOscillationGroupBox)
        self.yFreqUnits.setObjectName("yFreqUnits")
        self.horizontalLayout_4.addWidget(self.yFreqUnits)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.layoutWidget = QtWidgets.QWidget(GaussianCameraConfigForm)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 238, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.roiSizeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.roiSizeLabel.setObjectName("roiSizeLabel")
        self.horizontalLayout_6.addWidget(self.roiSizeLabel)
        self.roiSizeLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.roiSizeLineEdit.setObjectName("roiSizeLineEdit")
        self.horizontalLayout_6.addWidget(self.roiSizeLineEdit)
        spacerItem = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.xAmpLabel.setBuddy(self.xAmpLineEdit)
        self.xFreqLabel.setBuddy(self.xFreqLineEdit)
        self.yAmpLabel.setBuddy(self.yAmpLineEdit)
        self.yFreqLabel.setBuddy(self.yFreqLineEdit)
        self.roiSizeLabel.setBuddy(self.roiSizeLineEdit)

        self.retranslateUi(GaussianCameraConfigForm)
        QtCore.QMetaObject.connectSlotsByName(GaussianCameraConfigForm)

    def retranslateUi(self, GaussianCameraConfigForm):
        _translate = QtCore.QCoreApplication.translate
        GaussianCameraConfigForm.setWindowTitle(_translate("GaussianCameraConfigForm", "Form"))
        self.spotOscillationCheckBox.setText(_translate("GaussianCameraConfigForm", "Do Spot Oscillation"))
        self.spotOscillationGroupBox.setTitle(_translate("GaussianCameraConfigForm", "Spot Oscillation Parameters"))
        self.xAmpLabel.setText(_translate("GaussianCameraConfigForm", "X Amplitude:"))
        self.xAmpLineEdit.setToolTip(_translate("GaussianCameraConfigForm", "Valid Range: 1 to 20 pixels as an integer"))
        self.xAmpUnits.setText(_translate("GaussianCameraConfigForm", "pixel"))
        self.xFreqLabel.setText(_translate("GaussianCameraConfigForm", "X Frequency:"))
        self.xFreqLineEdit.setToolTip(_translate("GaussianCameraConfigForm", "Valid Range: 0.1 to 100 with an allowed precision of 1"))
        self.xFreqUnits.setText(_translate("GaussianCameraConfigForm", "Hz"))
        self.yAmpLabel.setText(_translate("GaussianCameraConfigForm", "Y Amplitude:"))
        self.yAmpLineEdit.setToolTip(_translate("GaussianCameraConfigForm", "Valid Range: 1 to 20 pixels as an integer"))
        self.yAmpUnits.setText(_translate("GaussianCameraConfigForm", "pixel"))
        self.yFreqLabel.setText(_translate("GaussianCameraConfigForm", "Y Frequency:"))
        self.yFreqLineEdit.setToolTip(_translate("GaussianCameraConfigForm", "Valid Range: 0.1 to 100 with an allowed precision of 1"))
        self.yFreqUnits.setText(_translate("GaussianCameraConfigForm", "Hz"))
        self.roiSizeLabel.setText(_translate("GaussianCameraConfigForm", "ROI Size:"))
        self.roiSizeLineEdit.setToolTip(_translate("GaussianCameraConfigForm", "Valid Range: 20 to 200 as an integer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GaussianCameraConfigForm = QtWidgets.QWidget()
    ui = Ui_GaussianCameraConfigForm()
    ui.setupUi(GaussianCameraConfigForm)
    GaussianCameraConfigForm.show()
    sys.exit(app.exec_())

