
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-11T22:42:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a8ab85af0b0b1c801a0d42a7225e91a7882e3b0b",
 "version": "v0.2.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
