
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-11T16:37:52-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e444192f170dad5a8c62225957a09bedea57fb26",
 "version": "1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
