[tool.poetry]
name = "py37-workspace"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"
ipython = "^7.9"
requests = "^2.22"
jupyter = "^1.0"
Alfred-Workflow = "^1.37"
pyppeteer = "^0.0.25"
openpyxl = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[[tool.poetry.source]]
name = 'aliyun.mirrors'
url = 'https://mirrors.aliyun.com/pypi/simple/'
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

