
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-10T12:30:44-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f7e9353302d1da98da9f00f2943a0e81e3731b1",
 "version": "1.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
