# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    List as typing___List,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
builtin___str = str


class Heartbeat(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Status(builtin___int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: builtin___int) -> builtin___str: ...
        @classmethod
        def Value(cls, name: builtin___str) -> 'Heartbeat.Status': ...
        @classmethod
        def keys(cls) -> typing___List[builtin___str]: ...
        @classmethod
        def values(cls) -> typing___List['Heartbeat.Status']: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[builtin___str, 'Heartbeat.Status']]: ...
        OK = typing___cast('Heartbeat.Status', 0)
        WARNING = typing___cast('Heartbeat.Status', 1)
        ERROR = typing___cast('Heartbeat.Status', 2)
        OFFLINE = typing___cast('Heartbeat.Status', 3)
    OK = typing___cast('Heartbeat.Status', 0)
    WARNING = typing___cast('Heartbeat.Status', 1)
    ERROR = typing___cast('Heartbeat.Status', 2)
    OFFLINE = typing___cast('Heartbeat.Status', 3)

    id = ... # type: typing___Text
    timestamp = ... # type: builtin___int
    status = ... # type: Heartbeat.Status

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        timestamp : typing___Optional[builtin___int] = None,
        status : typing___Optional[Heartbeat.Status] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Heartbeat: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"id",u"status",u"timestamp"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"status",b"status",u"timestamp",b"timestamp"]) -> None: ...
