# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from capabilities_pb2 import (
    Capability as capabilities_pb2___Capability,
)

from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from types_pb2 import (
    Type as types_pb2___Type,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class Config(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: typing___Text
    manufacturer = ... # type: typing___Text
    model = ... # type: typing___Text
    description = ... # type: typing___Text
    primaryType = ... # type: types_pb2___Type
    capabilities = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[capabilities_pb2___Capability]

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        manufacturer : typing___Optional[typing___Text] = None,
        model : typing___Optional[typing___Text] = None,
        description : typing___Optional[typing___Text] = None,
        primaryType : typing___Optional[types_pb2___Type] = None,
        capabilities : typing___Optional[typing___Iterable[capabilities_pb2___Capability]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> Config: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"capabilities",u"description",u"id",u"manufacturer",u"model",u"primaryType"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"capabilities",b"capabilities",u"description",b"description",u"id",b"id",u"manufacturer",b"manufacturer",u"model",b"model",u"primaryType",b"primaryType"]) -> None: ...

class StateUpdate(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: typing___Text
    timestamp = ... # type: builtin___int

    @property
    def state(self) -> google___protobuf___any_pb2___Any: ...

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        timestamp : typing___Optional[builtin___int] = None,
        state : typing___Optional[google___protobuf___any_pb2___Any] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> StateUpdate: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"state"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"id",u"state",u"timestamp"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"state",b"state"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"state",b"state",u"timestamp",b"timestamp"]) -> None: ...

class PairingUpdate(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: typing___Text
    timestamp = ... # type: builtin___int
    code = ... # type: typing___Text
    paired = ... # type: builtin___bool

    def __init__(self,
        *,
        id : typing___Optional[typing___Text] = None,
        timestamp : typing___Optional[builtin___int] = None,
        code : typing___Optional[typing___Text] = None,
        paired : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> PairingUpdate: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"code",u"id",u"paired",u"timestamp"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"code",b"code",u"id",b"id",u"paired",b"paired",u"timestamp",b"timestamp"]) -> None: ...
