# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: states.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='states.proto',
  package='device.state',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cstates.proto\x12\x0c\x64\x65vice.state\"\\\n\x06SWITCH\x12)\n\x05state\x18\x01 \x01(\x0e\x32\x1a.device.state.SWITCH.State\"\'\n\x05State\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03OFF\x10\x01\x12\x06\n\x02ON\x10\x02\x62\x06proto3'
)



_SWITCH_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='device.state.SWITCH.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFF', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ON', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=83,
  serialized_end=122,
)
_sym_db.RegisterEnumDescriptor(_SWITCH_STATE)


_SWITCH = _descriptor.Descriptor(
  name='SWITCH',
  full_name='device.state.SWITCH',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='device.state.SWITCH.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SWITCH_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=122,
)

_SWITCH.fields_by_name['state'].enum_type = _SWITCH_STATE
_SWITCH_STATE.containing_type = _SWITCH
DESCRIPTOR.message_types_by_name['SWITCH'] = _SWITCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SWITCH = _reflection.GeneratedProtocolMessageType('SWITCH', (_message.Message,), {
  'DESCRIPTOR' : _SWITCH,
  '__module__' : 'states_pb2'
  # @@protoc_insertion_point(class_scope:device.state.SWITCH)
  })
_sym_db.RegisterMessage(SWITCH)


# @@protoc_insertion_point(module_scope)
