
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-06T13:47:50-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2c3f01b2e9931da7b1d87aaa67c7e0c107c5fc7",
 "version": "0.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
