
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-15T08:53:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd886ff2b2cd19e8dc681245134cef8815d61f31",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
