# Generated by Django 3.0 on 2019-12-16 10:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledtasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='args',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, size=None),
        ),
    ]
