# Generated by Django 3.0 on 2019-12-16 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduledtasks', '0002_auto_20191216_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
