# Generated by Django 2.2.7 on 2019-12-12 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitech_notifier', '0002_auto_20191205_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitech_notifier_notifications', to='sitech_notifier.Event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitech_notifier_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
