- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - heat-translator-tox-py27-tp:
            voting: false

- job:
    name: heat-translator-tox-py27-tp
    parent: openstack-tox
    description: |
      Run tests for heat-translator project.

      Uses tox with the ``py27-tp`` environment.
    vars:
      tox_envlist: py27-tp
