# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoPolygonArray.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoPolygonArray.proto',
  package='org.openstreetmap.atlas.proto',
  syntax='proto2',
  serialized_options=b'B\030ProtoPolygonArrayWrapperP\001',
  serialized_pb=b'\n\x17ProtoPolygonArray.proto\x12\x1dorg.openstreetmap.atlas.proto\"4\n\x11ProtoPolygonArray\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tencodings\x18\x02 \x03(\x0c\x42\x1c\x42\x18ProtoPolygonArrayWrapperP\x01'
)




_PROTOPOLYGONARRAY = _descriptor.Descriptor(
  name='ProtoPolygonArray',
  full_name='org.openstreetmap.atlas.proto.ProtoPolygonArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.openstreetmap.atlas.proto.ProtoPolygonArray.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encodings', full_name='org.openstreetmap.atlas.proto.ProtoPolygonArray.encodings', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=110,
)

DESCRIPTOR.message_types_by_name['ProtoPolygonArray'] = _PROTOPOLYGONARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoPolygonArray = _reflection.GeneratedProtocolMessageType('ProtoPolygonArray', (_message.Message,), {
  'DESCRIPTOR' : _PROTOPOLYGONARRAY,
  '__module__' : 'ProtoPolygonArray_pb2'
  # @@protoc_insertion_point(class_scope:org.openstreetmap.atlas.proto.ProtoPolygonArray)
  })
_sym_db.RegisterMessage(ProtoPolygonArray)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
