# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import global_pb2 as global__pb2


class MecabStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Pos = channel.unary_unary(
        '/konlpy.v0alpha.Mecab/Pos',
        request_serializer=global__pb2.StringRequest.SerializeToString,
        response_deserializer=global__pb2.TupleArrayResponse.FromString,
        )
    self.Nouns = channel.unary_unary(
        '/konlpy.v0alpha.Mecab/Nouns',
        request_serializer=global__pb2.StringRequest.SerializeToString,
        response_deserializer=global__pb2.StringArrayResponse.FromString,
        )
    self.Morphs = channel.unary_unary(
        '/konlpy.v0alpha.Mecab/Morphs',
        request_serializer=global__pb2.StringRequest.SerializeToString,
        response_deserializer=global__pb2.StringArrayResponse.FromString,
        )


class MecabServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Pos(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Nouns(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Morphs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MecabServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Pos': grpc.unary_unary_rpc_method_handler(
          servicer.Pos,
          request_deserializer=global__pb2.StringRequest.FromString,
          response_serializer=global__pb2.TupleArrayResponse.SerializeToString,
      ),
      'Nouns': grpc.unary_unary_rpc_method_handler(
          servicer.Nouns,
          request_deserializer=global__pb2.StringRequest.FromString,
          response_serializer=global__pb2.StringArrayResponse.SerializeToString,
      ),
      'Morphs': grpc.unary_unary_rpc_method_handler(
          servicer.Morphs,
          request_deserializer=global__pb2.StringRequest.FromString,
          response_serializer=global__pb2.StringArrayResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'konlpy.v0alpha.Mecab', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
