version: 2

test-template: &test-template
    steps:
        - checkout
        - run:
                name: environment
                command: |
                    echo 'export PATH=.:$HOME/.local/bin:$PATH' >> $BASH_ENV
        - run:
                name: install
                command: |
                    pip install --progress-bar off --user -U -r requirements_dev.txt
                    sudo apt update -q
                    sudo apt upgrade -q
                    sudo apt install openjdk-11-jdk-headless
                    make install-kotlin-linters

        - run:
                name: lint
                command: make lint
        - run:
                name: install
                command: python setup.py install --user
        - run:
                name: test
                command: make test
        - run:
                name: make-docs
                command: |
                    make docs
                    touch docs/_build/html/.nojekyll
        - persist-to-workspace:
                root: docs/_build
                paths: html

jobs:
    build-37:
        docker:
            - image: circleci/python:3.7.5
        <<: *test-template

    build-38:
        docker:
            - image: circleci/python:3.8.0
        <<: *test-template

    docs-deploy:
        docker:
            - image: node:8.10.0
        steps:
            - checkout
            - add_ssh_keys:
                    fingerprints:
                        - "9b:25:aa:bf:39:b6:4a:e7:c3:52:cf:ab:23:81:3d:52"
            - attach_workspace:
                    at: docs/_build
            - run:
                    name: install
                    command: |
                        npm install -g --silent gh-pages@2.0.1
                        git config user.email "glean-ci@nowhere.com"
                        git config user.name "glean-ci"
            - run:
                    name: deploy
                    command: |
                        gh-pages --dotfiles --message "[ci skip] updates" --dist docs/_build/html

    pypi-deploy:
        docker:
            - image: circleci/python:3.7.5
        steps:
            - checkout
            - run:
                    name: environment
                    command: |
                        echo 'export PATH=.:$HOME/.local/bin:$PATH' >> $BASH_ENV
            - run:
                    name: install
                    command: |
                        pip install --user -U -r requirements_dev.txt
            - run:
                    name: deploy
                    # Requires that the TWINE_USERNAME and TWINE_PASSWORD environment
                    # variables are configured in CircleCI's environment variables.
                    command: |
                        make release

workflows:
    version: 2
    build:
        jobs:
            - build-37:
                    filters:
                        tags:
                            only: /.*/
            - build-38:
                    filters:
                        tags:
                            only: /.*/
            - docs-deploy:
                    requires:
                        - build-37
                    filters:
                        branches:
                            only: master
            - pypi-deploy:
                    requires:
                        - build-37
                    filters:
                        branches:
                            ignore: /.*/
                        tags:
                            only: /v[0-9]+(\.[0-9]+)*/
