
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "30d6f1451b16c5ab0742ae0c237ae29432797fc7",
 "version": "1.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
