[tool.poetry]
name = "django-enum-ex"
version = "0.1.1"
description = "一个基于 Django 3.0 Choices 枚举类型的独立包"
authors = ["codetalks <banxi1988@gmail.com>"]
readme = "README.md"
repository =  "https://github.com/banxi1988/django-enum-ex"
keywords = ["Django","Choices", "Enum","EnumField", "ChoicesField"]

[[tool.poetry.source]]
name = 'aliyun'
url = 'http://mirrors.aliyun.com/pypi/simple/'

[tool.poetry.dependencies]
python = "^3.6"
django = "^2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-cov = "^2.7"
pytest-django = "^3.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
