# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: forest_serialization.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='forest_serialization.proto',
  package='terminalmushroom.forest',
  syntax='proto3',
  serialized_options=_b('\252\002*VioletPines.TerminalMushroom.Serialization'),
  serialized_pb=_b('\n\x1a\x66orest_serialization.proto\x12\x17terminalmushroom.forest\",\n\x04Tree\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x10\n\x08\x62ranches\x18\x03 \x03(\r\"X\n\x06\x45ntity\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\r\n\x05\x61lias\x18\x02 \x01(\t\x12\x13\n\tincrement\x18\x03 \x01(\x05H\x00\x12\r\n\x03set\x18\x04 \x01(\x05H\x00\x42\x07\n\x05\x63ount\"\x9b\x01\n\x04Node\x12-\n\x04tree\x18\x01 \x01(\x0b\x32\x1d.terminalmushroom.forest.TreeH\x00\x12\x31\n\x06\x65ntity\x18\x02 \x01(\x0b\x32\x1f.terminalmushroom.forest.EntityH\x00\x12\x11\n\x07literal\x18\x03 \x01(\tH\x00\x12\x12\n\x08metadata\x18\x04 \x01(\tH\x00\x42\n\n\x08\x63ontents\"\xb8\x01\n\x06\x46orest\x12\x14\n\x0c\x65ntry_points\x18\x01 \x03(\r\x12\x10\n\x08\x65ntities\x18\x02 \x03(\t\x12\x39\n\x05nodes\x18\x03 \x03(\x0b\x32*.terminalmushroom.forest.Forest.NodesEntry\x1aK\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.terminalmushroom.forest.Node:\x02\x38\x01\x42-\xaa\x02*VioletPines.TerminalMushroom.Serializationb\x06proto3')
)




_TREE = _descriptor.Descriptor(
  name='Tree',
  full_name='terminalmushroom.forest.Tree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='terminalmushroom.forest.Tree.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='branches', full_name='terminalmushroom.forest.Tree.branches', index=1,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=99,
)


_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='terminalmushroom.forest.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='terminalmushroom.forest.Entity.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alias', full_name='terminalmushroom.forest.Entity.alias', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='increment', full_name='terminalmushroom.forest.Entity.increment', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set', full_name='terminalmushroom.forest.Entity.set', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='count', full_name='terminalmushroom.forest.Entity.count',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=101,
  serialized_end=189,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='terminalmushroom.forest.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tree', full_name='terminalmushroom.forest.Node.tree', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entity', full_name='terminalmushroom.forest.Node.entity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='literal', full_name='terminalmushroom.forest.Node.literal', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='terminalmushroom.forest.Node.metadata', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='contents', full_name='terminalmushroom.forest.Node.contents',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=192,
  serialized_end=347,
)


_FOREST_NODESENTRY = _descriptor.Descriptor(
  name='NodesEntry',
  full_name='terminalmushroom.forest.Forest.NodesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='terminalmushroom.forest.Forest.NodesEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='terminalmushroom.forest.Forest.NodesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=534,
)

_FOREST = _descriptor.Descriptor(
  name='Forest',
  full_name='terminalmushroom.forest.Forest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry_points', full_name='terminalmushroom.forest.Forest.entry_points', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entities', full_name='terminalmushroom.forest.Forest.entities', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='terminalmushroom.forest.Forest.nodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FOREST_NODESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=534,
)

_ENTITY.oneofs_by_name['count'].fields.append(
  _ENTITY.fields_by_name['increment'])
_ENTITY.fields_by_name['increment'].containing_oneof = _ENTITY.oneofs_by_name['count']
_ENTITY.oneofs_by_name['count'].fields.append(
  _ENTITY.fields_by_name['set'])
_ENTITY.fields_by_name['set'].containing_oneof = _ENTITY.oneofs_by_name['count']
_NODE.fields_by_name['tree'].message_type = _TREE
_NODE.fields_by_name['entity'].message_type = _ENTITY
_NODE.oneofs_by_name['contents'].fields.append(
  _NODE.fields_by_name['tree'])
_NODE.fields_by_name['tree'].containing_oneof = _NODE.oneofs_by_name['contents']
_NODE.oneofs_by_name['contents'].fields.append(
  _NODE.fields_by_name['entity'])
_NODE.fields_by_name['entity'].containing_oneof = _NODE.oneofs_by_name['contents']
_NODE.oneofs_by_name['contents'].fields.append(
  _NODE.fields_by_name['literal'])
_NODE.fields_by_name['literal'].containing_oneof = _NODE.oneofs_by_name['contents']
_NODE.oneofs_by_name['contents'].fields.append(
  _NODE.fields_by_name['metadata'])
_NODE.fields_by_name['metadata'].containing_oneof = _NODE.oneofs_by_name['contents']
_FOREST_NODESENTRY.fields_by_name['value'].message_type = _NODE
_FOREST_NODESENTRY.containing_type = _FOREST
_FOREST.fields_by_name['nodes'].message_type = _FOREST_NODESENTRY
DESCRIPTOR.message_types_by_name['Tree'] = _TREE
DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Forest'] = _FOREST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tree = _reflection.GeneratedProtocolMessageType('Tree', (_message.Message,), {
  'DESCRIPTOR' : _TREE,
  '__module__' : 'forest_serialization_pb2'
  # @@protoc_insertion_point(class_scope:terminalmushroom.forest.Tree)
  })
_sym_db.RegisterMessage(Tree)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY,
  '__module__' : 'forest_serialization_pb2'
  # @@protoc_insertion_point(class_scope:terminalmushroom.forest.Entity)
  })
_sym_db.RegisterMessage(Entity)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'forest_serialization_pb2'
  # @@protoc_insertion_point(class_scope:terminalmushroom.forest.Node)
  })
_sym_db.RegisterMessage(Node)

Forest = _reflection.GeneratedProtocolMessageType('Forest', (_message.Message,), {

  'NodesEntry' : _reflection.GeneratedProtocolMessageType('NodesEntry', (_message.Message,), {
    'DESCRIPTOR' : _FOREST_NODESENTRY,
    '__module__' : 'forest_serialization_pb2'
    # @@protoc_insertion_point(class_scope:terminalmushroom.forest.Forest.NodesEntry)
    })
  ,
  'DESCRIPTOR' : _FOREST,
  '__module__' : 'forest_serialization_pb2'
  # @@protoc_insertion_point(class_scope:terminalmushroom.forest.Forest)
  })
_sym_db.RegisterMessage(Forest)
_sym_db.RegisterMessage(Forest.NodesEntry)


DESCRIPTOR._options = None
_FOREST_NODESENTRY._options = None
# @@protoc_insertion_point(module_scope)
