
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-10T03:52:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "05c2cb63e57431471d05115da00e5cfb980b7879",
 "version": "2.0.0-beta.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
