# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: podder_task_foundation/api/protos/pipeline_framework.proto

import sys

from google.protobuf import (
    descriptor as _descriptor,
    message as _message,
    reflection as _reflection,
    symbol_database as _symbol_database,
)

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='podder_task_foundation/api/protos/pipeline_framework.proto',
    package='pipeline_framework',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n:podder_task_foundation/api/protos/pipeline_framework.proto\x12\x12pipeline_framework\"\xe3\x01\n\x17\x44\x61taTransferObjectGroup\x12\x0e\n\x06\x64\x61g_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x43\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x35.pipeline_framework.DataTransferObjectGroup.DataEntry\x12\x0e\n\x06\x65rrors\x18\x04 \x01(\t\x1aS\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.pipeline_framework.DataTransferObject:\x02\x38\x01\":\n\x12\x44\x61taTransferObject\x12\x10\n\x08\x64\x61tasets\x18\x01 \x01(\t\x12\x12\n\nproperties\x18\x02 \x01(\t2v\n\rPodderTaskApi\x12\x65\n\x07\x65xecute\x12+.pipeline_framework.DataTransferObjectGroup\x1a+.pipeline_framework.DataTransferObjectGroup\"\x00\x62\x06proto3'
    ))

_DATATRANSFEROBJECTGROUP_DATAENTRY = _descriptor.Descriptor(
    name='DataEntry',
    full_name='pipeline_framework.DataTransferObjectGroup.DataEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key',
            full_name='pipeline_framework.DataTransferObjectGroup.DataEntry.key',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value',
            full_name='pipeline_framework.DataTransferObjectGroup.DataEntry.value',
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=_b('8\001'),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=227,
    serialized_end=310,
)

_DATATRANSFEROBJECTGROUP = _descriptor.Descriptor(
    name='DataTransferObjectGroup',
    full_name='pipeline_framework.DataTransferObjectGroup',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='dag_id',
            full_name='pipeline_framework.DataTransferObjectGroup.dag_id',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='job_id',
            full_name='pipeline_framework.DataTransferObjectGroup.job_id',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='data',
            full_name='pipeline_framework.DataTransferObjectGroup.data',
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='errors',
            full_name='pipeline_framework.DataTransferObjectGroup.errors',
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[
        _DATATRANSFEROBJECTGROUP_DATAENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=83,
    serialized_end=310,
)

_DATATRANSFEROBJECT = _descriptor.Descriptor(
    name='DataTransferObject',
    full_name='pipeline_framework.DataTransferObject',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='datasets',
            full_name='pipeline_framework.DataTransferObject.datasets',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='properties',
            full_name='pipeline_framework.DataTransferObject.properties',
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=312,
    serialized_end=370,
)

_DATATRANSFEROBJECTGROUP_DATAENTRY.fields_by_name['value'].message_type = _DATATRANSFEROBJECT
_DATATRANSFEROBJECTGROUP_DATAENTRY.containing_type = _DATATRANSFEROBJECTGROUP
_DATATRANSFEROBJECTGROUP.fields_by_name['data'].message_type = _DATATRANSFEROBJECTGROUP_DATAENTRY
DESCRIPTOR.message_types_by_name['DataTransferObjectGroup'] = _DATATRANSFEROBJECTGROUP
DESCRIPTOR.message_types_by_name['DataTransferObject'] = _DATATRANSFEROBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataTransferObjectGroup = _reflection.GeneratedProtocolMessageType(
    'DataTransferObjectGroup',
    (_message.Message, ),
    dict(
        DataEntry=_reflection.GeneratedProtocolMessageType(
            'DataEntry',
            (_message.Message, ),
            dict(
                DESCRIPTOR=_DATATRANSFEROBJECTGROUP_DATAENTRY,
                __module__='podder_task_foundation.api.protos.pipeline_framework_pb2'
                # @@protoc_insertion_point(class_scope:pipeline_framework.DataTransferObjectGroup.DataEntry)
            )),
        DESCRIPTOR=_DATATRANSFEROBJECTGROUP,
        __module__='podder_task_foundation.api.protos.pipeline_framework_pb2'
        # @@protoc_insertion_point(class_scope:pipeline_framework.DataTransferObjectGroup)
    ))
_sym_db.RegisterMessage(DataTransferObjectGroup)
_sym_db.RegisterMessage(DataTransferObjectGroup.DataEntry)

DataTransferObject = _reflection.GeneratedProtocolMessageType(
    'DataTransferObject',
    (_message.Message, ),
    dict(
        DESCRIPTOR=_DATATRANSFEROBJECT,
        __module__='podder_task_foundation.api.protos.pipeline_framework_pb2'
        # @@protoc_insertion_point(class_scope:pipeline_framework.DataTransferObject)
    ))
_sym_db.RegisterMessage(DataTransferObject)

_DATATRANSFEROBJECTGROUP_DATAENTRY._options = None

_PODDERTASKAPI = _descriptor.ServiceDescriptor(
    name='PodderTaskApi',
    full_name='pipeline_framework.PodderTaskApi',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=372,
    serialized_end=490,
    methods=[
        _descriptor.MethodDescriptor(
            name='execute',
            full_name='pipeline_framework.PodderTaskApi.execute',
            index=0,
            containing_service=None,
            input_type=_DATATRANSFEROBJECTGROUP,
            output_type=_DATATRANSFEROBJECTGROUP,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_PODDERTASKAPI)

DESCRIPTOR.services_by_name['PodderTaskApi'] = _PODDERTASKAPI

# @@protoc_insertion_point(module_scope)
