[tool.poetry]
name = "speiseplan"
version = "0.1.6"
description = ""
authors = ["Markus Quade <info@markusqua.de>"]
license = "MIT"

[tool.poetry.scripts]
speiseplan = "speiseplan:main"

[tool.poetry.dependencies]
python = "^3.7"
requests_html = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
