# Generated by Django 2.1.13 on 2019-10-21 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('short_body', models.TextField(help_text='Short body with only necessary info, used in real-time notifications', verbose_name='Short body')),
                ('full_body_text', models.TextField(blank=True, null=True, verbose_name='Full plaintext body')),
                ('full_body_html', models.TextField(blank=True, null=True, verbose_name='Full HTML body')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
