[tool.poetry]
name = "psr-formats"
version = "0.2.1"
description = "Various formats used in pulsar signal processing"
authors = ["Dean Shaff <dshaff@swin.edu.au>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.16"
astropy = "^3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
