language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
matrix:
  include:
    - python: '3.7'
      env:
        - TOXENV=check
    - python: '3.6'
      env:
        - TOXENV=py36
#    - os: osx
#      python: '3.7'
#      language: generic
#      cache:
#        directories:
#          - $HOME/Library/Caches/Homebrew
#          - $HOME/Library/Caches/pip
#      env:
#        - TOXENV=py37
    - python: '3.7'
      env:
        - TOXENV=py37


before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install --progress-bar=off tox codecov -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
after_success:
    - codecov
