[build-system]
requires = ["setuptools>=30.3.0", "wheel", "setuptools_scm"]

[tool.black]
include = '\.pyi?$'
target-version = ['py36', 'py37']
exclude = '''
/(
    \.git
  | \.hg
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
