[tool.poetry]
name = "vidtag"
version = "0.1.7"
description = ""
authors = ["Oskar <oskar.alund@gmail.com>"]
include = ["*.py"]

[tool.poetry.dependencies]
python = "^3.7"
tqdm = "^4.40"
numpy = "^1.16"
tensorflow = "^2.0"
opencv-python = "^4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
vidtag = 'entry:main'
