
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-17T09:23:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7397ee04a61a564d29ac7a48f447cb62f78b1dc4",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
