# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20191205_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodelsingle',
            name='bear',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
