
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-05T14:54:17-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "27a9648d77d482a2f19ce585affcb4f9a2b1ea44",
 "version": "0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
