# Generated by Django 2.2.6 on 2019-11-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191106_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='agenda',
            field=models.CharField(blank=True, max_length=1024, verbose_name='日程'),
        ),
        migrations.AddField(
            model_name='post',
            name='agenda_order',
            field=models.CharField(blank=True, max_length=1024, verbose_name='议程顺序'),
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.CharField(blank=True, max_length=1024, verbose_name='持续时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='issue_no',
            field=models.CharField(default='xx1', max_length=255, verbose_name='问题编号'),
        ),
        migrations.AddField(
            model_name='post',
            name='issue_status',
            field=models.PositiveIntegerField(choices=[(0, 'OK'), (1, 'NOK')], default=1, verbose_name='问题状态'),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=1024, verbose_name='链接'),
        ),
        migrations.AddField(
            model_name='post',
            name='participants',
            field=models.CharField(blank=True, max_length=1024, verbose_name='与会人'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.CharField(blank=True, max_length=1024, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='post',
            name='task_code',
            field=models.CharField(blank=True, max_length=1024, verbose_name='任务编号'),
        ),
        migrations.AddField(
            model_name='post',
            name='task_content',
            field=models.CharField(blank=True, max_length=1024, verbose_name='任务内容'),
        ),
        migrations.AddField(
            model_name='post',
            name='week',
            field=models.CharField(blank=True, max_length=1024, verbose_name='会议周'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='问题标题'),
        ),
    ]
