# Generated by Django 2.2.6 on 2019-11-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191110_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='agenda',
            field=models.CharField(max_length=1024, verbose_name='日程'),
        ),
        migrations.AlterField(
            model_name='post',
            name='participants',
            field=models.CharField(max_length=1024, verbose_name='与会人'),
        ),
    ]
