# Generated by Django 2.2.6 on 2019-11-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20191112_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='task_category',
        ),
    ]
