
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-04T16:46:56-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c71aad387076abbe4a3bb2c5a50df3f81823afd0",
 "version": "0.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
