[tool.poetry]
name = "jrpytests"
version = "0.1.1"
description = ""
authors = ["Matteo Leo <matteoleo89@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.5"
pytest = "^3.0"
flake8=">=3.7.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
