language: python
os: linux
dist: xenial

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cargo"
    - "target"
    - ".tox"

branches:
  only:
  - master
  - "/^v.*$/"

script: tox

install: pip install tox-travis

jobs:
  allow_failures:
    - name: integration (ipfs/redis)
  include:
    - &check
      stage: check # do a pre-screen to make sure this is even worth testing
      python: 3.7

    - &test
      stage: test
      python: 2.7
    - <<: *test
      os: osx
      language: generic
      env:
        - TOXENV=py36
    - <<: *test
      python: 3.7
      name: integration (ipfs/redis)
      before_install:
        - sudo snap install ipfs
        - "/snap/bin/ipfs --version"
        - "/snap/bin/ipfs daemon --init --offline &>/dev/null &"
      services:
        - redis-server
        - docker
    - <<: *test
      python: 3.6
    - <<: *test
      python: 3.5
    - <<: *test
      name: wasm-pack
      language: rust
      rust: stable
      before_script: skip
      install: skip
      script:
        - rustup target add wasm32-unknown-unknown
        - cargo install --force wasm-pack
        - wasm-pack build
    - <<: *test
      name: wasi target
      language: rust
      rust: stable
      before_script: skip
      install: skip
      script:
        - rustup target add wasm32-wasi
        - cargo install --force cargo-wasi
        - cargo wasi build

    - &wheel
      stage: build wheel and send to github releases
      python: 3.7
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_SKIP='*-manylinux_i686'
      install: skip
      script:
        - sudo $PIP install cibuildwheel==1.0.0
        - cibuildwheel --output-dir wheelhouse
      deploy:
        provider: releases
        api_key:
          secure: "FZmx00gL0m0uNVN8fpvqbUZSI20EEk4sgrEv4wpGFr8SFNwPb/VuizQRTapeF2AW9qzbfbUv4bR/+oSKu5jxvd+7+p9HlOZT285a5yfxay9OA8YUbpQz4a9J0CETOpxrA2wRRWBDqzjEWzLTGUquOhyBZn4cwujvA9syOdB7OSNKsB6ARc+zhqPeoMKc9JcjzwiEIh7tcCHoZ1epN5zyfsjqFEY8XlylHTU/WSI3SS9KIGuBqWf6/haoYD7BH+f2g56GMHvBEmGjk5cf/lrCpqiho7Z3fGgJcYf3fRWM3qSVUM9JyHUIqPS6oPZIp7zP40TztiK4Oeen4EpcS/KdoSdu5CjfgMYgF/qdlL28ntgnVYhcA/6IDSRg6V4H3b20qjsn3NlaNVdsSNCu3GzkvM/dtvp5I/41XcFCNqMOljMr3tRw2ZVo44/1vYW0FB0b0FjhjNcnMyTOQjSRR78zetdoorewTJdEmxthMieHIw1Mqzwg4e6JvsC30sh1uSaFq4FHrj2Fe6lAlgwPs1e9vx4w0Zs0kxxusNAdbBB8FH8paFuUEGjgT0Jo9KHOLtvRy+OU2OacQePuhG1kGBRvJz7O4/prAFLGWIW8tyZDnMCuv1vmk6YZd6ih3omkL178X94pjzavtlUip/ugF0NIwS5o+zucRow9txAX2jXgDCM="
        file_glob: true
        file: wheelhouse/sourmash*.whl
        skip_cleanup: true
        on:
          tags: true
    - <<: *wheel
      os: osx
      osx_image: xcode10.1
      language: generic
      before_script:
        - sudo $PIP install -U pip setuptools
      env:
        - PIP=pip2
        - CIBW_ENVIRONMENT_MACOS='MACOSX_DEPLOYMENT_TARGET=10.11'

stages:
  - check
  - test
  - wheel
