
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-06T09:57:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "44e9a2d39a6f704728d24a530f467e03e9d41339",
 "version": "2019.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
