
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "321af0a5ae4c239ada9d288f82fce433735df71a",
 "version": "2228"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
