[tool.towncrier]
package = "asyncari"
filename = "docs/source/history.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/M-o-a-T/asyncari/issues/{issue}>`__"
