
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-11T11:11:29+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb401075ed0e4e1c5463d1ad11886528d1b8851c",
 "version": "1.8.68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
