---
- hosts: undercloud
  vars:
    metadata:
      name: Check Ironic boot configuration
      description: >
        Check if baremetal boot configuration is correct.
      groups:
        - pre-deployment
        - pre-upgrade
    deploy_kernel_name_base: "bm-deploy-kernel"
    deploy_ramdisk_name_base: "bm-deploy-ramdisk"
  roles:
    - ironic-boot-configuration
