#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['rasa_language']

package_data = \
{'': ['*'],
 'rasa_language': ['.pytest_cache/*',
                   '.pytest_cache/v/*',
                   '.pytest_cache/v/cache/*']}

install_requires = \
['lark-parser>=0.7.8', 'Click>=7.0', 'colorama>=0.4.3', 'PyYAML==5.2']

entry_points = \
{'console_scripts': ['rasa_language = rasa_language.__main__:main']}

setup(name='rasa_language',
      version='0.0.1',
      description='An attempt of crafting a specific purpose language for describing rasa chatbots',
      author='Ícaro Pires e João Robson',
      author_email=None,
      url='https://github.com/icaropires/rasa-chatbot-description-language',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
