# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0006_auto_20160523_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedorganization',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seedpermission',
            name='namespace',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seedpermission',
            name='object_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seedpermission',
            name='type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seedteam',
            name='title',
            field=models.TextField(),
        ),
    ]
