
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8b90b9ed78fd7ec12b519c954ff65676846a3440",
 "version": "2223"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
