sudo: false 
language: python

matrix: 
  include: 
    - 
      addons: 
        apt: 
          packages: 
            - g++-4.9
            - gcc-4.9
          sources: 
            - ubuntu-toolchain-r-test
      env: 
        - PYTHONPATH=$PWD
        - CC=gcc-4.9
        - CXX=g++-4.9
      os: linux
      python: "3.6"
    - 
      addons: 
        apt: 
          packages: 
            - g++-5
            - gcc-5
          sources: 
            - ubuntu-toolchain-r-test
      env: 
        - PYTHONPATH=$PWD
        - CC=gcc-5
        - CXX=g++-5
      os: linux
      python: "3.6"
    - 
      addons: 
        apt: 
          packages: 
            - g++-6
            - gcc-6
          sources: 
            - ubuntu-toolchain-r-test
      env: 
        - PYTHONPATH=$PWD
        - CC=gcc-6
        - CXX=g++-6
      os: linux
      python: "3.6"
    - 
      addons: 
        apt: 
          packages: 
            - g++-7
            - gcc-7
          sources: 
            - ubuntu-toolchain-r-test
      env: 
        - PYTHONPATH=$PWD
        - CC=gcc-7
        - CXX=g++-7
      os: linux
      python: "3.6"
    - 
      addons: 
        apt: 
          packages: 
            - g++-8
            - gcc-8
          sources: 
            - ubuntu-toolchain-r-test
      env: 
        - PYTHONPATH=$PWD
        - CC=gcc-8
        - CXX=g++-8
      os: linux
      python: "3.6"
    - addons: 
        homebrew:
            packages:
              - openssl
              - python3
      env:
        - PYTHONPATH=$PWD
        - HOMEBREW_NO_AUTO_UPDATE=1
      language: sh
      os: osx
      osx_image: xcode11
      before_install:
        - pip install pytest
    - addons: 
        homebrew:
          packages:
                - openssl
                - python3
      env: 
        - PYTHONPATH=$PWD
        - CC=gcc-9
        - CXX=g++-9
        - HOMEBREW_NO_AUTO_UPDATE=1
      language: sh
      os: osx
      osx_image: xcode11
      before_install:
        - pip install pytest
script: 
  - "pip install -e ."
  - "py.test -svx test.py"