
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "855733dd21ba4da1ab0d0dd57e14744897974c98",
 "version": "0.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
