
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-01T19:41:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f72bd9a3f307b323b6783f05ebf212afde6dc94c",
 "version": "0.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
