# Generated by Django 2.2.2 on 2019-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezybaas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamodel',
            name='ondelete',
            field=models.CharField(blank=True, choices=[('No Foreign Key', 'No Foreign Key'), ('CASCADE', 'CASCADE'), ('PROTECT', 'PROTECT'), ('SET_NULL', 'SET_NULL'), ('SET_DEFAULT', 'SET_DEFAULT')], default='No Foreign Key', max_length=100),
        ),
    ]
