
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-10T09:16:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c399e06e257f06a87e546f590e6472e3e6f02149",
 "version": "4.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
