
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-10T13:46:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7c3e858e57b6e8f2c7e43d909c1026fb46ce93c",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
