[tool.poetry]
name = "asyncify"
version = "0.2.2"
description = ""
authors = ["jessekrubin <jessekrubin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pytest-asyncio = "^0.10.0"


[tool.poetry.dev-dependencies]
pytest = "^5.2"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
