
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-05T22:57:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1c5f7c2c52d320be9c8223ed2c7cd5bdba39330",
 "version": "0.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
