[tool.poetry]
name = "pyRBI"
version = "0.1.0"
description = ""
authors = ["Felipe Rodrigues <felipe@felipevr.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
pre-commit = "^1.20"
pylint = "^2.4"
ipython = "^7.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
