# Generated by Django 2.2.6 on 2019-11-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20191112_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='task_category',
        ),
    ]
