# Generated by Django 2.2.5 on 2019-09-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=128)),
                ('fileType', models.CharField(max_length=128)),
                ('location', models.CharField(choices=[('GCL', 'Google Cloud Storage'), ('AWS', 'Amazon Web Services Storage')], default='GCL', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
