# Generated by Django 2.2.5 on 2019-09-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.URLField(),
        ),
    ]
