# Generated by Django 2.2.5 on 2019-09-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20190924_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='hash',
            field=models.CharField(default='NONE', max_length=128),
        ),
    ]
