# Generated by Django 2.2.6 on 2019-11-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_fileupload_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='status',
            field=models.CharField(default='OK', max_length=128),
        ),
    ]
