[tool.poetry]
name = "playlistzip"
version = "0.1.0"
description = ""
authors = ["Ross Vorotynskij <ross@rvcg.net>"]
license = "GPL-3.0+"

[tool.poetry.dependencies]
python = "^3.7"
jsonpath-rw = "^1.4"
pycurl = "^7.43"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
plz = 'playlistzip.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
