[tool.poetry]
name = "django-ninja"
version = "0.1.0"
description = ""
authors = ["Vitaliy Kucheriavyi <ppr.vitaly@gmail.com>"]
packages = [
    { include = "ninja" },
]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
