[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"


[tool.flit.metadata]
module = "distributionPackage"
author = "Russell Smiley"
author-email = "im.russell.smiley@gmail.com"
home-page = "https://gitlab.com/blueskyjunkie/distribution-package"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
description-file = "README.rst"
keywords = "manifest package distribution file"

requires-python = ">=3"

requires = [ "packageManifest" ]


[tool.flit.metadata.requires-extra]
dev = [
    "pygments",
]


[tool.flit.scripts]
makePackage = "distributionPackage:entrypoint"
