# Generated by Django 2.2.5 on 2019-10-02 11:24

from django.db import migrations, models
import typeform_feedback.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_feedback', '0003_auto_20191002_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generictypeformfeedback',
            name='quiz_slug',
            field=models.CharField(default=typeform_feedback.helpers.random_string, max_length=256, unique=True),
        ),
    ]
