# coding: utf-8

# flake8: noqa

"""
    Dyspatch API

    # Introduction  The Dyspatch API is based on the REST paradigm and features resource based URLs with standard HTTP response codes to indicate errors. We use standard HTTP authentication and request verbs and all responses are JSON formatted. See our [Implementation Guide](https://docs.dyspatch.io/development/implementing_dyspatch/) for more details on how to implement Dyspatch.  ## API Client Libraries  Dyspatch provides API Clients for the following languages and web frameworks:  - [Java](https://github.com/getdyspatch/dyspatch-java) - [Javascript](https://github.com/getdyspatch/dyspatch-javascript) - [Python](https://github.com/getdyspatch/dyspatch-python) - [C#](https://github.com/getdyspatch/dyspatch-dotnet) - [Go](https://github.com/getdyspatch/dyspatch-golang) - [Ruby](https://github.com/getdyspatch/dyspatch-ruby)   # noqa: E501

    OpenAPI spec version: 2019.10
    Contact: support@dyspatch.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from dyspatch_client.api.drafts_api import DraftsApi
from dyspatch_client.api.localizations_api import LocalizationsApi
from dyspatch_client.api.templates_api import TemplatesApi

# import ApiClient
from dyspatch_client.api_client import ApiClient
from dyspatch_client.configuration import Configuration
# import models into sdk package
from dyspatch_client.models.api_error import APIError
from dyspatch_client.models.body import Body
from dyspatch_client.models.compiled_read import CompiledRead
from dyspatch_client.models.created_at import CreatedAt
from dyspatch_client.models.cursor import Cursor
from dyspatch_client.models.draft_description import DraftDescription
from dyspatch_client.models.draft_id import DraftId
from dyspatch_client.models.draft_meta_read import DraftMetaRead
from dyspatch_client.models.draft_name import DraftName
from dyspatch_client.models.draft_read import DraftRead
from dyspatch_client.models.draft_url import DraftUrl
from dyspatch_client.models.drafts_read import DraftsRead
from dyspatch_client.models.language_id import LanguageId
from dyspatch_client.models.localization_id import LocalizationId
from dyspatch_client.models.localization_key_read import LocalizationKeyRead
from dyspatch_client.models.localization_meta_read import LocalizationMetaRead
from dyspatch_client.models.localization_name import LocalizationName
from dyspatch_client.models.localization_read import LocalizationRead
from dyspatch_client.models.localization_url import LocalizationUrl
from dyspatch_client.models.template_description import TemplateDescription
from dyspatch_client.models.template_id import TemplateId
from dyspatch_client.models.template_meta_read import TemplateMetaRead
from dyspatch_client.models.template_name import TemplateName
from dyspatch_client.models.template_read import TemplateRead
from dyspatch_client.models.template_url import TemplateUrl
from dyspatch_client.models.templates_read import TemplatesRead
from dyspatch_client.models.updated_at import UpdatedAt
