
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-04T14:04:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c454fa55dc21a439df0911cd191ddb03667bb56d",
 "version": "v0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
