
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "27a9ac970d3cce3a580e832c93b1349c28093283",
 "version": "3.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
