# Generated by Django 2.2.8 on 2019-12-14 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='mods',
            field=models.ManyToManyField(
                blank=True, related_name='mods', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(
                blank=True, related_name='users', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
