[tool.poetry]
name = "pytzkt"
version = "0.1.1"
description = "TzKT API wrapper"
authors = ["AO <aopoltorzhicky@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
