# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 17:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgqueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
