
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-16T11:56:58-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "92fff401dca233bb830aad1b548c5709cb8b36d5",
 "version": "0.4.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
