[tool.poetry]
name = "automatic-behavior-analysis"
version = "0.0.15"
description = "Program complex for automated behavior analysis"
authors = ["Aleksandr Sinitca <siniza.s.94@gmail.com>", "Michael Plazner <mplazner@campus.haifa.ac.il>"]
packages = [
    { include = "client2" },
    { include = "client2/tools" },
    { include = "client" },
    { include = "server" },
    { include = "analitics" },
    { include = "util" },
    { include = "tools" },
]
readme = "README.md"
repository = "https://gitlab.com/digiratory/automatic-behavior-analysis/"
classifiers = [
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Medical Science Apps."
]

[tool.poetry.scripts]
aba-client = 'client2:run.main'

[tool.poetry.dependencies]
python = "^3.6"
appdirs = ""
PyQt5 = ""
opencv-python = ""
scipy = ""
pandas = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
