[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "briar_repl"
author = "fphemeral"
author-email = "fphemeral@i2pmail.org"
home-page = "https://code.briarproject.org/fphemeral/briar_repl"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]

