# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-07-17 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.IntegerField()),
                ('action', models.CharField(choices=[('c', 'Create'), ('u', 'Update'), ('d', 'Delete')], max_length=10)),
                ('model', models.CharField(max_length=100)),
                ('identity_id', models.UUIDField()),
                ('subscription_id', models.UUIDField(null=True)),
                ('detail', models.TextField(null=True)),
            ],
        ),
    ]
