# Generated by Django 2.2.5 on 2019-09-25 13:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergenerictypeformfeedback',
            name='response',
        ),
        migrations.AddField(
            model_name='generictypeformfeedback',
            name='typeform_id',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='usergenerictypeformfeedback',
            name='_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
