# Generated by Django 2.2.5 on 2019-10-10 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_feedback', '0004_auto_20191002_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergenerictypeformfeedback',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
