# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20160714_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelAdvanced2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(blank=True, choices=[('', 'Empty'), ('set1', '1'), ('set2', '2'), ('set3', '3')], max_length=20, verbose_name='Selection')),
                ('set1_1', models.CharField(blank=True, max_length=20)),
                ('set2_1', models.CharField(blank=True, max_length=20)),
                ('set2_2', models.CharField(blank=True, max_length=20)),
                ('set2_3', models.CharField(blank=True, max_length=20)),
                ('set3_1', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='testinlinemodel',
            name='parent2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.TestModelAdvanced2'),
        ),
    ]
