# Generated by Django 2.2.7 on 2019-11-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_testmodelsingle2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodeladvanced',
            name='set',
            field=models.CharField(blank=True, choices=[('', 'Empty'), ('set1', '1'), ('set2', '2'), ('set3_1', '3')], max_length=20, verbose_name='Selection'),
        ),
        migrations.AlterField(
            model_name='testmodeladvanced2',
            name='set',
            field=models.CharField(blank=True, choices=[('', 'Empty'), ('set1', '1'), ('set2', '2'), ('set3_1', '3')], max_length=20, verbose_name='Selection'),
        ),
    ]
