# coding: utf-8

"""
    Nomad Hawk

    This is the API descriptor for the Nomad Hawk API, responsible for tracking and analytics.  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import nomad_hawk_cli
from nomad_hawk_cli.models.api_response_connector_response import ApiResponseConnectorResponse  # noqa: E501
from nomad_hawk_cli.rest import ApiException


class TestApiResponseConnectorResponse(unittest.TestCase):
    """ApiResponseConnectorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiResponseConnectorResponse(self):
        """Test ApiResponseConnectorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nomad_hawk_cli.models.api_response_connector_response.ApiResponseConnectorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
