
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-12-06T13:37:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0619f565b1e82a86d2d02467a5f4f5016c60f9c",
 "version": "2019.12.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
