#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['Tictactoe_anany']

package_data = \
{'': ['*']}

setup(name='Tictactoe_anany',
      version='1.0.0',
      description='Tic Tac Toe game just for fun, made by Anany Singh',
      author='Anany Singh',
      author_email='programmer.anany.singh@gmail.com',
      url=None,
      packages=packages,
      package_data=package_data,
     )
