[tool.poetry]
name = "sprawl"
version = "0.1.1"
description = ""
authors = ["Levi Notik <projects@levinotik.com>"]
readme="README.md"

[tool.poetry.dependencies]
python = "^3.7"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
