repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3

-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort
      language_version: python3

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    - id: flake8
      language_version: python3
      additional_dependencies: ['flake8-comprehensions~=2.2.0', 'pep8-naming~=0.8.2', 'flake8-black~=0.1.0']
