# Generated by Django 2.2.6 on 2019-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20191106_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_content',
            field=models.TextField(max_length=1024, verbose_name='待办事宜'),
        ),
    ]
