# Generated by Django 2.2.6 on 2019-11-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20191108_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category',
            new_name='task_category',
        ),
    ]
