# Generated by Django 2.2.6 on 2019-11-10 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20191108_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterField(
            model_name='task',
            name='closed_date',
            field=models.DateField(auto_now=True, verbose_name='.__关 闭 日 期__.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='task',
            name='raised_date',
            field=models.DateField(auto_now=True, verbose_name='.__提 出 日 期__.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.CharField(max_length=255, verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(auto_now=True, verbose_name='.__目 标 日 期__.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='task.TaskCategory', verbose_name='部    门'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.PositiveIntegerField(choices=[(3, 'R'), (2, 'Y'), (1, 'G')], default=2, verbose_name='STA'),
        ),
    ]
