# Generated by Django 2.2.6 on 2019-11-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20191112_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.PositiveIntegerField(choices=[(3, 'R'), (2, 'Y'), (1, 'G')], default=2, verbose_name='STA'),
        ),
    ]
