
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-12T15:34:49-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "11d29ef1013d39ee680d35c5523ab83b8bf3edcd",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
