# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deploy_arguments.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deploy_arguments.proto',
  package='exonum.java.runtime',
  syntax='proto3',
  serialized_options=_b('\n\037com.exonum.binding.core.runtimeP\001'),
  serialized_pb=_b('\n\x16\x64\x65ploy_arguments.proto\x12\x13\x65xonum.java.runtime\",\n\x0f\x44\x65ployArguments\x12\x19\n\x11\x61rtifact_filename\x18\x01 \x01(\tB#\n\x1f\x63om.exonum.binding.core.runtimeP\x01\x62\x06proto3')
)




_DEPLOYARGUMENTS = _descriptor.Descriptor(
  name='DeployArguments',
  full_name='exonum.java.runtime.DeployArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='artifact_filename', full_name='exonum.java.runtime.DeployArguments.artifact_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['DeployArguments'] = _DEPLOYARGUMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeployArguments = _reflection.GeneratedProtocolMessageType('DeployArguments', (_message.Message,), dict(
  DESCRIPTOR = _DEPLOYARGUMENTS,
  __module__ = 'deploy_arguments_pb2'
  # @@protoc_insertion_point(class_scope:exonum.java.runtime.DeployArguments)
  ))
_sym_db.RegisterMessage(DeployArguments)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
