
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2019-03-24T19:40:53-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "aff713a6884a0ebf2214af5cfa3c1ea2d7d70669",
 "version": "0.14.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
