# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: komoran.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import global_pb2 as global__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='komoran.proto',
  package='konlpy.v0alpha',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rkomoran.proto\x12\x0ekonlpy.v0alpha\x1a\x0cglobal.proto2\xee\x01\n\x07Komoran\x12H\n\x03Pos\x12\x1d.konlpy.v0alpha.StringRequest\x1a\".konlpy.v0alpha.TupleArrayResponse\x12K\n\x05Nouns\x12\x1d.konlpy.v0alpha.StringRequest\x1a#.konlpy.v0alpha.StringArrayResponse\x12L\n\x06Morphs\x12\x1d.konlpy.v0alpha.StringRequest\x1a#.konlpy.v0alpha.StringArrayResponseb\x06proto3')
  ,
  dependencies=[global__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_KOMORAN = _descriptor.ServiceDescriptor(
  name='Komoran',
  full_name='konlpy.v0alpha.Komoran',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=48,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='Pos',
    full_name='konlpy.v0alpha.Komoran.Pos',
    index=0,
    containing_service=None,
    input_type=global__pb2._STRINGREQUEST,
    output_type=global__pb2._TUPLEARRAYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Nouns',
    full_name='konlpy.v0alpha.Komoran.Nouns',
    index=1,
    containing_service=None,
    input_type=global__pb2._STRINGREQUEST,
    output_type=global__pb2._STRINGARRAYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Morphs',
    full_name='konlpy.v0alpha.Komoran.Morphs',
    index=2,
    containing_service=None,
    input_type=global__pb2._STRINGREQUEST,
    output_type=global__pb2._STRINGARRAYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KOMORAN)

DESCRIPTOR.services_by_name['Komoran'] = _KOMORAN

# @@protoc_insertion_point(module_scope)
