class ExToolsError(RuntimeError):
    """A custom runtime exception for errors generated by ExTools.

    :param trigger_exc: the original exception that triggered this one.
    :type trigger_exc: Exception
    """
    def __init__(self, trigger_exc=None):
        self.trigger_exc = trigger_exc
