# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-03-26 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False, 'verbose_name': 'Foo', 'verbose_name_plural': 'Foo',
            },
        ),
    ]
