weather:
  - platform: openweathermap
    api_key: use_ais_dom_api_key

sensor:
  - platform: darksky
    api_key: use_ais_dom_api_key
    forecast: 0
    language: pl
    units: si
    monitored_conditions:
      # A human-readable text summary for the next two days.
      - hourly_summary
      # A human-readable text summary for the next week.
      - daily_summary
      - temperature
      # feels like
      - apparent_temperature
      - wind_speed
      - cloud_cover
      - humidity
      - pressure
      - visibility
    scan_interval:
      hours: 2

group:
  ais_pogoda:
    name: Pogoda
    entities:
      - sensor.dark_sky_temperature
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_humidity
      - sensor.dark_sky_pressure
      - sensor.dark_sky_visibility
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_daily_summary
