
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-11T19:56:05-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3b10746531136e271c24e399d2bc87a7f7707f0",
 "version": "3.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
