
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-03T19:12:22-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6fcda086255484a0a777c5b8d55c7736f9659e6",
 "version": "1.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
