dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: v9T3N0ak+VL+DdAVurMPcDS+GIXSt8DFNCfXZwC7SUK5Yen5pWeeY4Ul+qt5KUUrgzawQQwrPt7wj1YPWQvusvVN1FNGTrua9JCnGFY113ij+MeniZOiAC2prROhaa1n+Cjm8eOSgCWFiNYxR30YrcDI4LovHVrrcocdcMfo5w0GXryIRMIKTGSVD5mISCPV/QXqv5lNkY0wpNZ8edjj8xVrPtZvVldWNSNsezkyFlzdHNtXLm3SuL7Zk8uCWuEVooKQosofe8uBKiOF4WZXFh+45bBZ5UzaGtUsK/Gm2Xdmy2KfWbmJXyTUkI4Zc74fmGASmV3e2L5taI813HOizl8kjTV3BvO7NuvutSqgeZy4Jod7H/yrfp6lIjP9PdyY6typnLg5j1pXElz52xqk3oUkTGG6FuEeMIION4H6zxptOPD8wxVvhHQW9C5iICI/Zwas7fP8ksVzR3IiwmynogilzmEGaW1p4oMycfSZ/ZKALmHfWh4370GD5JB4d9dO+HRdGuJzOZj0g2/zus3RMWzet4uQDtiLw7P9PJ9vHpjBOo5OWvqOYk4Ll08IZ0aMe+qdPUg8/JQ2/zd5Jus6quI3CfT/gZfZuVZ/ATG8hZFx9xNAW6JTQw5Ca+2DC8ghuQve2ohf8bYd25wW5JV5bpOuLiZRC/m/EOa+yBLJNko=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_ds18x20.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-ds18x20 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
