
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-13T14:20:03+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "fcd0c7fbcdd61ea16510055dba91967ddb3361f4",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
