
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-16T00:24:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3937ac54bb6b5929bc36639e977737caef1e11b2",
 "version": "0.10.13.post.dev57"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
