
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-09T15:37:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "73e7d0ed10bdc8a54368cd448fe3c38d98c9bf2f",
 "version": "0.9.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
