
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-03T13:00:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "78642838d2091ed85ef6f45c416ec3002ec3ce8f",
 "version": "0.4.97"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
