[tool.poetry]
name = "jrpyml"
version = "0.3.1"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.5"
sklearn = "^0.0.0"
numpy = "^1.15"
pandas = "^0.23.4"
matplotlib = "^3.0"
seaborn = "^0.9.0"
graphviz = "^0.10.1"
flake8 = ""

[tool.poetry.dev-dependencies]
pytest = "^3.0"
