
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-13T09:47:16-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b31dff8e0f67c6fc9b5c4e7b00ab1c58fff5ef37",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
