[tool.poetry]
name = "aws-credentials"
version = "0.2.1"
description = "AWS credential manager"
authors = ["Paul Robertson <t.paulrobertson@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/perobertson/aws-credentials"
keywords = [
  "access",
  "aws",
  "credentials",
  "iam",
  "rotate",
  "token"
]

[tool.poetry.dependencies]
python = "^3.5"
boto3 = "^1.9"
click = "^7.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-import-order = "^0.18.1"
ipdb = "^0.12.2"
pytest = "^5.2.1"
pytest-cov = "^2.8.1"
toml = "^0.10.0"

[tool.poetry.scripts]
aws-credentials = 'aws_credentials.cli:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
