[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "trvaep"
author = "Mohammad Lotfollahi"
author-email = "mohammad.lotfollahi@helmholtz-muenchen.de"
classifiers = ["License :: OSI Approved :: MIT License"]

