#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['trvaep', 'trvaep.model']

package_data = \
{'': ['*']}

setup(name='trvaep',
      version='0.0',
      description='trVAE - Transfer Variational Autoencoders pytorch',
      author='Mohammad Lotfollahi',
      author_email='mohammad.lotfollahi@helmholtz-muenchen.de',
      url=None,
      packages=packages,
      package_data=package_data,
     )
