
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-07T22:46:07+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "58484148c547aafbf5a6fff49ddbfc6932dc7e1a",
 "version": "2.0.0-beta.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
