# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0008_auto_20160610_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedpermission',
            name='object_id',
            field=models.TextField(null=True),
        ),
    ]
