# Generated by Django 2.2.6 on 2019-11-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='closed_date',
            field=models.DateField(auto_now=True, verbose_name='关闭日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(auto_now=True, verbose_name='目标日期'),
        ),
    ]
