
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-04T17:53:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7d0c8fdb79fa8e38d0f3f5eeaf2d7846c8cbcbf",
 "version": "0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
