
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-14T11:52:10-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a7b5ea4e20904548106f644aa67b49eb2977aa3e",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
