[tool.poetry]
name = "monitor-common"
version = "0.1.2"
description = "Common code used for the internet monitor app."
authors = ["George Blackburn <g-a-b@hotmail.co.uk>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/Malrig/monitor-common"
repository = "https://gitlab.com/Malrig/monitor-common"
include = [
    "LICENSE.md",
]

[tool.poetry.dependencies]
python = "^3.6"
mongoengine = "^0.18.2"
aenum = "^2.2"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = "^2.8"
docker = "^4.1"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
mypy = "^0.740.0"
flake8 = "^3.7"
pydocstyle = "^4.0"
safety = "^1.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
