# Generated by Django 2.2.8 on 2019-12-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191214_2243'),
    ]

    operations = [
        migrations.RenameField(model_name='message', old_name='author', new_name='user',),
    ]
