# Autogenerated by Astropy's setup.py on 2019-12-07 20:18:24 UTC
import datetime

version = "4.0rc2"
githash = "d88eee5014695e2bc5cadb14d492e42d77fd0f17"


major = 4
minor = 0
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2019, 12, 7, 20, 18, 24)
debug = False

astropy_helpers_version = "4.0.rc1"
