[tool.poetry]
name = "jrpyprogramming"
version = "0.1.10"
description = ""
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.5"
pandas = ">=0.20.3, <0.24"
numpy = "^1.14.4"
matplotlib = ">=3.0"

[tool.poetry.dev-dependencies]
