# Generated by Django 2.1.8 on 2019-09-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCoverPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อ')),
                ('html', models.TextField(blank=True, default='<table onclick="websiteCoverPage.close()">\n  <tr>\n    <td>\n      <img src="/path/to/image.png" />\n    </td>\n  </tr>\n</table>', verbose_name='HTML')),
                ('style', models.TextField(blank=True, default='#websitecoverpage {\n  background: rgba(0, 0, 0, 0.5);\n  height: 100vh;\n  left: 0;\n  position: fixed;\n  right: 0;\n  top: 0;\n  z-index: 9999998;\n}\n\n#websitecoverpage table, tr {\n  height: 100vh;\n  width: 100%;\n}\n\n#websitecoverpage td {\n  padding: 25px;\n  text-align: center;\n  vertical-align: middle;\n}\n\n#websitecoverpage img {\n  box-shadow: 0px 0px 25px 5px rgba(0, 0, 0, 0.5);\n  cursor: pointer;\n  max-width: 800px;\n  width: 100%;\n}', verbose_name='CSS')),
                ('start_datetime', models.DateTimeField(verbose_name='เวลาเริ่มต้น')),
                ('end_datetime', models.DateTimeField(verbose_name='เวลาสิ้นสุด')),
            ],
            options={
                'verbose_name': 'Cover page',
                'verbose_name_plural': 'Cover pages',
                'ordering': ('start_datetime', 'end_datetime', 'name'),
            },
        ),
    ]
