# Deprecated as config-download is now the default.
resource_registry:
  OS::TripleO::SoftwareDeployment: OS::Heat::StructuredDeployment
  OS::TripleO::Ssh::HostPubKey: ../extraconfig/tasks/ssh/host_public_key.yaml
  OS::TripleO::Ssh::KnownHostsDeployment: OS::Heat::StructuredDeployments
  OS::TripleO::DeploymentSteps: OS::Heat::StructuredDeploymentGroup
