language: python
dist: xenial
cache: pip
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 'pypy3'
install: travis_retry pip install tox-travis codecov
script: tox -v
after_success: codecov --required -X gcov fix pycov -f coverage.xml --flags ${TOXENV//-/ }
branches:
  except: templates/1.5.x templates/1.6.x
stages:
- test
- name: deploy
  if: repo = jazzband/django-configurations AND tag IS present
jobs:
  include:
  - stage: test
  - stage: deploy
    install: skip
    script: skip
    python: 3.7
    env: skip
    deploy:
      provider: pypi
      user: jazzband
      server: https://jazzband.co/projects/django-configurations/upload
      distributions: sdist bdist_wheel
      password:
        secure: LuserSjUTGSsls9zrvck/FbfL+gFpNU/ywOQ/67ufEbbpGCeDBEgxDzgb0acfHNk8wlAkaPvaAejQBFtcUulhdNT/g0NsmaEAjd6HhCGM+FRJAnYFaj33Js6C+N2tX5wznL7uCBxqgtaaH0hf6ucqC8OXqwoCVGgdxAEnUlC/fY=
      on:
        tags: true
        repo: jazzband/django-configurations
