[tool.poetry]
name = "argson"
version = "0.3.0"
description = "Declare program arguments from JSON"
authors = ["Gabriel Chamon Araujo <gchamon@live.com>"]

[tool.poetry.dependencies]
python = "^3.6"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
