[tool.poetry]
name = "ReCAP-Argument-Graph"
version = "0.1.1"
description = ""
authors = ["Mirko Lenz <info@mirko-lenz.de>"]

[tool.poetry.dependencies]
python = "^3.7"
pygraphviz = "^1.5"
networkx = "^2.4"
spacy = "^2.2"
pendulum = "^2.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = {version = "^18.3-alpha.0", allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
