
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-06T18:06:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ee4ad7f53712dfbec253c5c8406f4eccff31bb5f",
 "version": "3.2.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
