[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "dnnv"
author = "David Shriver"
author-email = "dls2fc@virginia.edu"
description-file="README.md"
requires=[
    "numpy==1.16.4",
    "onnx==1.6",
    "psutil==5.6.5",
    "scipy==1.3",
    "tensorflow==1.14",
    "keras==2.3",
]
requires-python=">=3.6"

[tool.flit.metadata.requires-extra]
test = [
    "torchvision==0.2",
]
doc = ["sphinx"]

[tool.flit.scripts]
dnnv = "dnnv.__main__:_main"
