
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "30d205fa77d6f57e356b62310be873e82c884508",
 "version": "0.20.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
