
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-17T14:57:34+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ad5adf716cf5e507ea25a144aa1ba7a670f1542",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
