# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("identities", "0005_optin")]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="failed_message_count",
            field=models.IntegerField(
                default=0, help_text=b"Count of consecutive failed messages to user"
            ),
        )
    ]
