
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-05T18:28:13-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "39a7ddcb65c7dcacca8ac5531c238fef87916979",
 "version": "1.1.16rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
