
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e6efad98a7f677aba45ac6427f922a6d08189317",
 "version": "3.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
