
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a18ae80a90fd8f990bd7a5b0838deab03d89b3e0",
 "version": "2.8.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
