
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-17T16:11:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "177b0a94b0135b2971110fbcf72c32ea7596e170",
 "version": "2019.12.17.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
