# Generated by Django 2.2 on 2019-12-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.UUIDField()),
                ('exc_type', models.CharField(blank=True, max_length=512, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('traceback', models.TextField()),
            ],
            options={
                'verbose_name': 'Error Message',
                'verbose_name_plural': 'Error Messages',
            },
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chat_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bot',
            },
        ),
    ]
