[tool.poetry]
name = "mozci"
version = "0.1.5"
description = ""
authors = [
  "Andrew Halberstadt <ahal@mozilla.com>",
  "Marco Castelluccio <marco@mozilla.com>",
]

[tool.poetry.dependencies]
python = "^3.7"
adr = "^0.16.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.3"
tox = "^3.14"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
