
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-16T01:26:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9978517cec4f673b87c31d4db634046c34d24daa",
 "version": "v0.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
