
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-08T20:39:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "79f68b1ac90641f4565adf43e11e7bf862950e6a",
 "version": "0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
