
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-04T01:34:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e48a2cbd6e7562a53f55a59e8ab32371925cf028",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
