[tool.poetry]
name = "matrix-saml-strip-hostname"
version = "0.1.0"
description = "SAML mapping provider to strip hostnames from mxids"
authors = ["Sylvain Fankhauser <sephi@fhtagn.top>"]

[tool.poetry.dependencies]
python = ">=3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
