# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("identities", "0006_identity_failed_message_count")]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="failed_message_count",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text=b"Count of consecutive failed messages to user",
                null=True,
            ),
        )
    ]
