# Generated by Django 2.1.4 on 2019-02-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("identities", "0008_auto_20181213_1443")]

    operations = [
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["-created_at"], name="identities__created_9b7633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["-updated_at"], name="identities__updated_f35b8c_idx"
            ),
        ),
    ]
