
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "29191127e5f10edc86f8a9ec0a544928e9339faa",
 "version": "0.5.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
