
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-07T15:21:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "31c5b7e6cb30b7a4dc43779c55d55fc75102320b",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
