language: python
python: 3.7
dist: xenial
matrix:
  include:
    - name: "Defaults (Python 3.7)"
    - name: "Python 3.6"
      python: "3.6"
    - name: "Python 3.5"
      python: "3.5"
    - name: "Code Lint"
      env:
        - LINT=1
      install:
        - pip install flake8
script:
 - ./runtests.sh
