
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f096b0e8d35691bc15d94a96a2914b45b495bf77",
 "version": "0+untagged.2.gf096b0e"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
