[tool.poetry]
name = "terminalmushroom"
version = "3.0.1"
description = ""
authors = ["Coriander Pines <1647914-cvpines@users.noreply.gitlab.com>"]

[tool.poetry.dependencies]
python = "^3.6"
protobuf = "^3.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
