
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-06T08:08:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7eeadbfe36c8d6bcc2e16ee929fcca6b658e3f0",
 "version": "0.73.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
