heat_template_version: rocky

parameters:
  servers:
    type: json

resources:
  StandaloneStandardExtraConfigPost:
    type: ../../extraconfig/post_deploy/standalone_post.yaml
    properties:
       servers:  {get_param: servers}

  IronicVBMCSetup:
    type: vbmc_setup.yaml
    properties:
       servers:  {get_param: servers}

