[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "flit_bumpversion"
author = "Niels Lemmens"
author-email = "draso.odin@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=3.7"

[tool.flit.scripts]
flit-bumpversion = "flit_bumpversion.__main__:cli"
