# coding: utf-8

"""
    tfjob

    Python SDK for TF-Operator  # noqa: E501

    OpenAPI spec version: v0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import tfjob
from tfjob.models.v1_job_status import V1JobStatus  # noqa: E501
from tfjob.rest import ApiException


class TestV1JobStatus(unittest.TestCase):
    """V1JobStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1JobStatus(self):
        """Test V1JobStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tfjob.models.v1_job_status.V1JobStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
