[tool.poetry]
name = "jrpyoop"
version = "0.1.6"
description = ""
authors = ["Colin <colin@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = "^0.23.4"
matplotlib = "^3.1"

[tool.poetry.dev-dependencies]
