# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoIntegerArrayOfArrays.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ProtoIntegerArray_pb2 as ProtoIntegerArray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoIntegerArrayOfArrays.proto',
  package='org.openstreetmap.atlas.proto',
  syntax='proto2',
  serialized_options=b'B ProtoIntegerArrayOfArraysWrapperP\001',
  serialized_pb=b'\n\x1fProtoIntegerArrayOfArrays.proto\x12\x1dorg.openstreetmap.atlas.proto\x1a\x17ProtoIntegerArray.proto\"k\n\x19ProtoIntegerArrayOfArrays\x12\x0c\n\x04name\x18\x01 \x01(\t\x12@\n\x06\x61rrays\x18\x02 \x03(\x0b\x32\x30.org.openstreetmap.atlas.proto.ProtoIntegerArrayB$B ProtoIntegerArrayOfArraysWrapperP\x01'
  ,
  dependencies=[ProtoIntegerArray__pb2.DESCRIPTOR,])




_PROTOINTEGERARRAYOFARRAYS = _descriptor.Descriptor(
  name='ProtoIntegerArrayOfArrays',
  full_name='org.openstreetmap.atlas.proto.ProtoIntegerArrayOfArrays',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.openstreetmap.atlas.proto.ProtoIntegerArrayOfArrays.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arrays', full_name='org.openstreetmap.atlas.proto.ProtoIntegerArrayOfArrays.arrays', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=198,
)

_PROTOINTEGERARRAYOFARRAYS.fields_by_name['arrays'].message_type = ProtoIntegerArray__pb2._PROTOINTEGERARRAY
DESCRIPTOR.message_types_by_name['ProtoIntegerArrayOfArrays'] = _PROTOINTEGERARRAYOFARRAYS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoIntegerArrayOfArrays = _reflection.GeneratedProtocolMessageType('ProtoIntegerArrayOfArrays', (_message.Message,), {
  'DESCRIPTOR' : _PROTOINTEGERARRAYOFARRAYS,
  '__module__' : 'ProtoIntegerArrayOfArrays_pb2'
  # @@protoc_insertion_point(class_scope:org.openstreetmap.atlas.proto.ProtoIntegerArrayOfArrays)
  })
_sym_db.RegisterMessage(ProtoIntegerArrayOfArrays)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
