# Generated by Django 2.2.6 on 2019-11-12 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191112_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='task_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='task.TaskCategory', verbose_name='部门'),
        ),
    ]
