
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d7a27bdc2a28febf1750f4d35ef0b3587980d882",
 "version": "2.8.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
