# Generated by Django 2.2.6 on 2019-11-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191110_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='issue_status',
            field=models.PositiveIntegerField(choices=[(0, 'OK'), (1, 'NOK')], verbose_name='问题状态'),
        ),
    ]
