name: aeolus_docs
channels:
- conda-forge
dependencies:
- python=3.7
- cartopy
- iris
- matplotlib
- metpy>=0.11
- nbsphinx
- numpy
- pip
- pyvista
- sphinx
- sphinx_rtd_theme
- xarray
- pip:
  - latlon23
