
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-11T22:21:14+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc337b9cb9ac5b68f31c18663bd46bb18c0be5d1",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
