dist: bionic
sudo: false
language: python
env:
    global:
        - BOTO_CONFIG=/dev/null
matrix:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 2.7
          env: TOXENV=py27-next
        - python: 3.5
          env: TOXENV=py35
        - python: 3.5
          env: TOXENV=py35-next
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=py36-3.0
        - python: 3.6
          env: TOXENV=py36-next
        - python: 3.7
          env: TOXENV=py37
        - python: 3.7
          env: TOXENV=py37-3.0
        - python: 3.7
          env: TOXENV=py37-next
        - python: 3.8
          env: TOXENV=py38
        - python: 3.8
          env: TOXENV=py38-3.0
        - python: 3.8
          env: TOXENV=py38-next
    allow_failures:
        - env: TOXENV=py36-3.0
        - env: TOXENV=py37-3.0
        - env: TOXENV=py38-3.0
        - env: TOXENV=py27-next
        - env: TOXENV=py35-next
        - env: TOXENV=py36-next
        - env: TOXENV=py37-next
        - env: TOXENV=py38-next
services:
    - redis-server
-before_install:
    - pip install --upgrade setuptools pip
install:
    - pip install --upgrade tox
script:
    - tox
after_success:
    - tox -e codecov
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: mozillasecurity
    password:
        secure: IUdzz9q5UgZ8kk2NQjMcmDerAt+RCbaV3+3oYxvvzxsh2lfNjFSnuqL2Nl/jN+1hI/qH2iKNOZUvzZegUP3CACC0ZW0MXs46XJUbzprBubvfUS1YlvAkLPGvjXlJrcxIIiLNicdSoqOALSg1OUM18DbIVUaL4RZm2qBltMXcELo=
    on:
        tags: true
        python: 2.7
