
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-12T05:36:10-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3261c1ed4dda6e72ea6ccb36eabb7cc081bb7526",
 "version": "v0.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
