[tool.poetry]
name = "geek"
version = "0.1.1"
description = ""
authors = ["Vlad Dmitrievich <me@2tunnels.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
python-slugify = "^4.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"

[tool.poetry.scripts]
geek = 'geek.console:run'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
