sudo: false

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

addons:
  apt:
    packages:
      - make
      - gcc
      - qemu-utils
      - xorriso
      - zlib1g-dev

before_script:
  - export PATH=$PATH:$PWD/bin
  - export PREFIX=$PWD

install:
  - pip install --upgrade pip setuptools
  - pip install tox-travis
  - pip install codecov

cache:
  apt: true
  directories:
    - $HOME/.cache/pip

script: tox

after_success:
  if [ -z "$TRAVIS_TAG" ]; then
    codecov;
  else
    echo "Tag build ($TRAVIS_TAG). Not uploading coverage.";
  fi
