languages:
   Python: true
pep8:
  enabled: true
  checks:
    E501:
      enabled: false
exclude_paths:
- ".pylintrc"
- "LICENSE"
- "test/*"
- "docs/*"
- "*.in"
- "*.txt"
- "*.cfg"
- "*.rst"
- "*.ini"
- "*.yml"
- "*.*.yml"
