# Generated by Django 2.2.6 on 2019-12-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_task_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Issue', 'verbose_name_plural': 'Issue'},
        ),
    ]
