[tool.poetry]
name = "reposync"
version = "0.6.0"
description = "Organize git repositories."
authors = ["Devin Alvaro <devin.alvaro@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
fire = "^0.2.1"
gitpython = "^3.0.5"
pyaml = "^19.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
