[tool.poetry]
name = "vbml"
version = "0.5.0"
description = "Way to check"
authors = ["timoniq"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
