
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-09T12:28:07-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8aa73afaf4bb1f8db8e324340e0f61a7fb6e6da",
 "version": "1.16.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
