# Generated by Django 2.0.1 on 2018-11-19 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('ohm2_handlers_light', '0001_initial'), ('ohm2_handlers_light', '0002_auto_20181119_2052')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('app', models.CharField(max_length=255)),
                ('code', models.IntegerField(default=-1)),
                ('message', models.TextField(default='')),
                ('extra', models.TextField(default='')),
                ('ins_filename', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ins_lineno', models.IntegerField(blank=True, default=0, null=True)),
                ('ins_function', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('ins_code_context', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
