# Generated by Django 2.0.1 on 2018-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohm2_handlers_light', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseerror',
            name='app',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='baseerror',
            name='identity',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='baseerror',
            name='ins_filename',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baseerror',
            name='ins_function',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
