
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-14T18:15:30-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4f627bfb2ea99eb9d1ad9ef9fe0e338f3e3cf2a",
 "version": "1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
