
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-14T15:54:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1678818fab5c5457529721f51616002893b246f7",
 "version": "0.6.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
