# Generated by Django 2.2.6 on 2019-11-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20191110_2200'),
        ('blog', '0011_auto_20191112_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='task_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='task.TaskCategory', verbose_name='部门'),
        ),
    ]
