# Generated by Django 2.2.6 on 2019-11-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='task_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='task.TaskCategory', verbose_name='部门'),
        ),
    ]
