
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "720df3a8af5d00036525da15afba354315c41bc6",
 "version": "1.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
