[package]
name = "rustpy-tools"
description = "A useful tool Python module implement in rust-lang."
version = "0.2.1"
authors = ["leohowell.com@gmail.com"]
readme = "README.md"
edition = "2018"
repository = "https://github.com/leohowell/rustpy-tools"
homepage = "https://github.com/leohowell/rustpy-tools"
license = "BSD-2-Clause"

[dependencies]
pyo3 = { version = "0.8.3", features = ["extension-module"] }
regex = { version = "1.3.1"}
rust-crypto = "^0.2"
base64 = "0.11.0"

[lib]
name = "rustpy_tools"
crate-type = ["cdylib"]
