###############################################################################
# Role: OpenShiftWorker                                                            #
###############################################################################
- name: OpenShiftWorker
  description: |
    OpenShiftWorker role
  CountDefault: 1
  RoleParametersDefault:
    OpenShiftNodeGroupName: 'node-config-compute'
    DockerSkipUpdateReconfiguration: true
  tags:
    - openshift
  networks:
    InternalApi:
      subnet: internal_api_subnet
    Storage:
      subnet: storage_subnet
  # For systems with both IPv4 and IPv6, you may specify a gateway network for
  # each, such as ['ControlPlane', 'External']
  default_route_networks: ['ControlPlane']
  update_serial: 25
  ServicesDefault:
    - OS::TripleO::Services::BootParams
    - OS::TripleO::Services::Docker
    - OS::TripleO::Services::OpenShift::GlusterFS
    - OS::TripleO::Services::OpenShift::Worker
    - OS::TripleO::Services::Podman
    - OS::TripleO::Services::Rhsm
    - OS::TripleO::Services::Sshd
    - OS::TripleO::Services::Timesync
    - OS::TripleO::Services::TripleoFirewall
