
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-12-11T17:36:02+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2dda6e65709e3aebaf0b91c388bdca2bb16cd159",
 "version": "0.5.0-alpha.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
